using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using Jenga.Core;
using Jenga.Enemies;
using Jenga.Inventory;
using Jenga.Items;
using Jenga.Loot;
using Jenga.Player;
using Jenga.Shop;
using Jenga.UI;
using Jenga.Waves;

namespace Jenga.EditorTools
{
    /// <summary>
    /// Genera todo el contenido jugable del proyecto: sprites, materiales,
    /// modelos 3D, prefabs, ScriptableObjects y la escena de juego.
    /// Menú: Jenga > Generar contenido del juego.
    /// </summary>
    public static class JengaContentGenerator
    {
        const string Root = "Assets/Generated";
        const string IconsFolder = Root + "/Icons";
        const string MaterialsFolder = Root + "/Materials";
        const string PrefabsFolder = Root + "/Prefabs";
        const string ItemsFolder = Root + "/Items";
        const string EnemiesFolder = Root + "/Enemies";
        const string ConfigFolder = Root + "/Config";
        const string ResourcesFolder = "Assets/Resources";
        const string ScenePath = "Assets/Scenes/Game.unity";
        const string DatabasePath = ResourcesFolder + "/GameDatabase.asset";

        const int LayerPlayer = 8;
        const int LayerEnemy = 9;
        const int LayerLoot = 10;

        static Dictionary<string, Sprite> _icons;
        static Dictionary<string, Material> _materials;

        [MenuItem("Jenga/Generar contenido del juego", priority = 0)]
        public static void GenerateFromMenu()
        {
            bool exists = AssetDatabase.LoadAssetAtPath<GameDatabase>(DatabasePath) != null;
            if (exists && !EditorUtility.DisplayDialog(
                    "Regenerar contenido",
                    "Se volverán a crear los assets generados (iconos, materiales, prefabs, objetos, enemigos, oleadas y la escena Game.unity).\n\nSe perderán los ajustes manuales hechos sobre esos assets.",
                    "Regenerar", "Cancelar"))
                return;

            Generate(true);
        }

        [MenuItem("Jenga/Abrir escena de juego", priority = 1)]
        public static void OpenGameScene()
        {
            if (!File.Exists(ScenePath))
            {
                if (EditorUtility.DisplayDialog("Escena no encontrada",
                        "Todavía no se ha generado la escena. ¿Generar el contenido ahora?", "Generar", "Cancelar"))
                    Generate(true);
                return;
            }
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene(ScenePath);
        }

        const string AutoRunKey = "Jenga.AutoGenerated";
        static int _framesWaited;

        /// <summary>
        /// Primera vez que se abre el proyecto: crea el contenido si aún no existe.
        /// Se espera unos frames en vez de usar EditorApplication.delayCall porque ese
        /// callback es un delegado multicast: si otro sistema del editor lanza una
        /// excepción antes (por ejemplo el indexador de UnityEditor.Search), el resto
        /// de la cadena no llega a ejecutarse y la generación se quedaría sin hacer.
        /// </summary>
        [InitializeOnLoadMethod]
        static void AutoGenerateOnFirstLoad()
        {
            if (SessionState.GetBool(AutoRunKey, false)) return;
            _framesWaited = 0;
            EditorApplication.update -= WaitForIdleThenGenerate;
            EditorApplication.update += WaitForIdleThenGenerate;
        }

        static void WaitForIdleThenGenerate()
        {
            // Deja que el editor termine de importar, compilar e indexar.
            if (EditorApplication.isCompiling || EditorApplication.isUpdating) return;
            if (++_framesWaited < 30) return;

            EditorApplication.update -= WaitForIdleThenGenerate;

            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            if (SessionState.GetBool(AutoRunKey, false)) return;
            SessionState.SetBool(AutoRunKey, true);
            if (AssetDatabase.LoadAssetAtPath<GameDatabase>(DatabasePath) != null) return;

            try
            {
                Debug.Log("[Jenga] Generando el contenido del juego por primera vez...");
                Generate(false);
            }
            catch (System.Exception e)
            {
                Debug.LogError("[Jenga] Falló la generación automática. Usa el menú " +
                               "Jenga > Generar contenido del juego para reintentarlo.\n" + e);
            }
        }

        public static void Generate(bool openScene)
        {
            try
            {
                EditorUtility.DisplayProgressBar("Jenga", "Creando carpetas...", 0f);
                EnsureFolders();

                EditorUtility.DisplayProgressBar("Jenga", "Dibujando sprites...", 0.1f);
                _icons = IconPainter.GenerateAll(IconsFolder);

                EditorUtility.DisplayProgressBar("Jenga", "Creando materiales...", 0.25f);
                _materials = CreateMaterials();

                EditorUtility.DisplayProgressBar("Jenga", "Construyendo modelos y prefabs...", 0.4f);
                var weaponModels = CreateWeaponModels();
                var lootPrefab = CreateLootPrefab();

                EditorUtility.DisplayProgressBar("Jenga", "Creando objetos y armas...", 0.55f);
                var items = CreateItems();
                var weapons = CreateWeapons(weaponModels);

                EditorUtility.DisplayProgressBar("Jenga", "Creando enemigos y oleadas...", 0.7f);
                var enemies = CreateEnemies(items);
                var waveConfig = CreateWaveConfig(enemies);
                var shopStock = CreateShopStock(items, weapons);

                EditorUtility.DisplayProgressBar("Jenga", "Creando el jugador...", 0.8f);
                var playerPrefab = CreatePlayerPrefab(weapons["pistol"], items);

                EditorUtility.DisplayProgressBar("Jenga", "Guardando la base de datos...", 0.88f);
                var database = CreateDatabase(items, weapons, enemies, waveConfig, lootPrefab);

                EditorUtility.DisplayProgressBar("Jenga", "Montando la escena...", 0.94f);
                BuildScene(playerPrefab, database, waveConfig, shopStock, openScene);

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
                Debug.Log("[Jenga] Contenido generado. Abre Assets/Scenes/Game.unity y pulsa Play.");
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }
        }

        // ------------------------------------------------------------ carpetas

        static void EnsureFolders()
        {
            string[] folders =
            {
                Root, IconsFolder, MaterialsFolder, PrefabsFolder, ItemsFolder,
                EnemiesFolder, ConfigFolder, ResourcesFolder, "Assets/Scenes"
            };
            foreach (var f in folders)
            {
                if (AssetDatabase.IsValidFolder(f)) continue;
                Directory.CreateDirectory(f);
            }
            AssetDatabase.Refresh();
        }

        static T CreateOrReplace<T>(string path) where T : ScriptableObject
        {
            var existing = AssetDatabase.LoadAssetAtPath<T>(path);
            if (existing != null) return existing;
            var asset = ScriptableObject.CreateInstance<T>();
            AssetDatabase.CreateAsset(asset, path);
            return asset;
        }

        // ---------------------------------------------------------- materiales

        static Material Mat(string name, Color color, float smoothness, float metallic, Color? emission = null)
        {
            string path = $"{MaterialsFolder}/{name}.mat";
            var shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null) shader = Shader.Find("Standard");

            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            mat.SetColor("_BaseColor", color);
            mat.SetColor("_Color", color);
            if (mat.HasProperty("_Smoothness")) mat.SetFloat("_Smoothness", smoothness);
            if (mat.HasProperty("_Glossiness")) mat.SetFloat("_Glossiness", smoothness);
            if (mat.HasProperty("_Metallic")) mat.SetFloat("_Metallic", metallic);

            if (emission.HasValue)
            {
                mat.EnableKeyword("_EMISSION");
                mat.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
                mat.SetColor("_EmissionColor", emission.Value);
            }
            EditorUtility.SetDirty(mat);
            return mat;
        }

        static Material UnlitAdditive(string name, Color color)
        {
            string path = $"{MaterialsFolder}/{name}.mat";
            var shader = Shader.Find("Universal Render Pipeline/Unlit");
            if (shader == null) shader = Shader.Find("Sprites/Default");

            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            mat.SetColor("_BaseColor", color);
            mat.SetColor("_Color", color);
            if (mat.HasProperty("_Surface")) mat.SetFloat("_Surface", 1f);
            if (mat.HasProperty("_Blend")) mat.SetFloat("_Blend", 2f);
            mat.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.One);
            mat.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.One);
            mat.SetInt("_ZWrite", 0);
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.DisableKeyword("_ALPHAPREMULTIPLY_ON");
            mat.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;
            EditorUtility.SetDirty(mat);
            return mat;
        }

        static Dictionary<string, Material> CreateMaterials()
        {
            return new Dictionary<string, Material>
            {
                { "ground", Mat("M_Ground", new Color(0.18f, 0.19f, 0.22f), 0.15f, 0f) },
                { "grid", Mat("M_GroundAccent", new Color(0.24f, 0.28f, 0.34f), 0.25f, 0f) },
                { "wall", Mat("M_Wall", new Color(0.30f, 0.33f, 0.39f), 0.2f, 0.1f) },
                { "cover", Mat("M_Cover", new Color(0.38f, 0.34f, 0.28f), 0.15f, 0f) },
                { "enemy", Mat("M_Enemy", Color.white, 0.25f, 0.05f) },
                { "enemyDark", Mat("M_EnemyDark", new Color(0.22f, 0.22f, 0.26f), 0.2f, 0.1f) },
                { "gunBody", Mat("M_GunBody", new Color(0.42f, 0.45f, 0.50f), 0.55f, 0.85f) },
                { "gunDark", Mat("M_GunDark", new Color(0.14f, 0.15f, 0.18f), 0.45f, 0.7f) },
                { "wood", Mat("M_Wood", new Color(0.36f, 0.24f, 0.15f), 0.2f, 0f) },
                { "accent", Mat("M_Accent", new Color(0.25f, 0.85f, 1f), 0.6f, 0f, new Color(0.2f, 0.9f, 1.3f)) },
                { "gold", Mat("M_Gold", new Color(1f, 0.82f, 0.3f), 0.7f, 0.9f, new Color(0.6f, 0.45f, 0.1f)) },
                { "tracer", UnlitAdditive("M_Tracer", new Color(1f, 0.85f, 0.4f)) },
                { "impact", UnlitAdditive("M_Impact", new Color(1f, 0.7f, 0.35f)) },
            };
        }

        // -------------------------------------------------------- modelos 3D

        static Dictionary<string, GameObject> CreateWeaponModels()
        {
            var result = new Dictionary<string, GameObject>();
            var body = _materials["gunBody"];
            var dark = _materials["gunDark"];
            var accent = _materials["accent"];
            var wood = _materials["wood"];

            result["pistol"] = SavePrefab(ModelFactory.BuildPistol(body, dark, accent), $"{PrefabsFolder}/Model_Pistol.prefab");
            result["rifle"] = SavePrefab(ModelFactory.BuildRifle(body, dark, accent), $"{PrefabsFolder}/Model_Rifle.prefab");
            result["shotgun"] = SavePrefab(ModelFactory.BuildShotgun(body, dark, wood), $"{PrefabsFolder}/Model_Shotgun.prefab");
            return result;
        }

        static GameObject SavePrefab(GameObject instance, string path)
        {
            var prefab = PrefabUtility.SaveAsPrefabAsset(instance, path);
            Object.DestroyImmediate(instance);
            return prefab;
        }

        static GameObject CreateLootPrefab()
        {
            var root = new GameObject("LootPickup");
            root.layer = LayerLoot;

            var spin = ModelFactory.Empty("Spin", root.transform, new Vector3(0f, 0.35f, 0f));

            var iconGo = new GameObject("Icon");
            iconGo.transform.SetParent(spin, false);
            iconGo.transform.localScale = Vector3.one * 0.75f;
            iconGo.layer = LayerLoot;
            var sr = iconGo.AddComponent<SpriteRenderer>();
            sr.sprite = _icons["icon_coin"];
            iconGo.AddComponent<Billboard>();

            ModelFactory.Part("Glow", PrimitiveType.Sphere, spin, Vector3.zero, Vector3.one * 0.16f, _materials["accent"]);
            ModelFactory.Part("Ring", PrimitiveType.Cylinder, root.transform, new Vector3(0f, 0.02f, 0f), new Vector3(0.55f, 0.02f, 0.55f), _materials["accent"]);

            var drop = root.AddComponent<LootDrop>();
            FieldWriter.On(drop)
                .Ref("iconRenderer", sr)
                .Ref("spinRoot", spin)
                .Apply();

            return SavePrefab(root, $"{PrefabsFolder}/LootPickup.prefab");
        }

        // ------------------------------------------------------------- objetos

        static ItemData MakeItem(string file, string id, string display, string description, string iconKey,
            ItemCategory category, int price, float sellRatio, int maxStack, Color tint)
        {
            var item = CreateOrReplace<ItemData>($"{ItemsFolder}/{file}.asset");
            item.itemId = id;
            item.displayName = display;
            item.description = description;
            item.icon = _icons.TryGetValue(iconKey, out var s) ? s : null;
            item.category = category;
            item.basePrice = price;
            item.sellRatio = sellRatio;
            item.maxStack = maxStack;
            item.tint = tint;
            item.canDrop = true;
            EditorUtility.SetDirty(item);
            return item;
        }

        static Dictionary<string, ItemData> CreateItems()
        {
            var items = new Dictionary<string, ItemData>();

            items["scrap"] = MakeItem("Item_Chatarra", "item.scrap", "Chatarra",
                "Restos metálicos de los autómatas destruidos. No sirven para nada salvo para venderlos.",
                "icon_scrap", ItemCategory.Material, 14, 0.6f, 99, Color.white);

            items["circuit"] = MakeItem("Item_Circuito", "item.circuit", "Circuito dañado",
                "Placa de control aún reparable. Los comerciantes pagan bien por ellas.",
                "icon_circuit", ItemCategory.Material, 45, 0.6f, 99, Color.white);

            items["core"] = MakeItem("Item_Nucleo", "item.core", "Núcleo inestable",
                "Fuente de energía de un autómata élite. Vale una fortuna y pesa muy poco.",
                "icon_core", ItemCategory.Material, 130, 0.65f, 20, Color.white);

            var medkit = CreateOrReplace<ConsumableData>($"{ItemsFolder}/Item_Botiquin.asset");
            medkit.itemId = "item.medkit";
            medkit.displayName = "Botiquín";
            medkit.description = "Kit de campaña. Restaura una buena parte de la vida al instante.";
            medkit.icon = _icons["icon_medkit"];
            medkit.category = ItemCategory.Consumable;
            medkit.basePrice = 65;
            medkit.sellRatio = 0.5f;
            medkit.maxStack = 5;
            medkit.healAmount = 45f;
            medkit.ammoAmount = 0;
            EditorUtility.SetDirty(medkit);
            items["medkit"] = medkit;

            var ammo = CreateOrReplace<ConsumableData>($"{ItemsFolder}/Item_Municion.asset");
            ammo.itemId = "item.ammo";
            ammo.displayName = "Caja de munición";
            ammo.description = "Recarga la munición de reserva del arma que lleves equipada.";
            ammo.icon = _icons["icon_ammo"];
            ammo.category = ItemCategory.Ammo;
            ammo.basePrice = 50;
            ammo.sellRatio = 0.5f;
            ammo.maxStack = 8;
            ammo.healAmount = 0f;
            ammo.ammoAmount = 90;
            EditorUtility.SetDirty(ammo);
            items["ammo"] = ammo;

            return items;
        }

        static Dictionary<string, WeaponData> CreateWeapons(Dictionary<string, GameObject> models)
        {
            var weapons = new Dictionary<string, WeaponData>();

            var pistol = CreateOrReplace<WeaponData>($"{ItemsFolder}/Weapon_Pistola.asset");
            pistol.itemId = "weapon.pistol";
            pistol.displayName = "Pistola PX-9";
            pistol.description = "Arma reglamentaria. Fiable, precisa y barata de mantener.";
            pistol.icon = _icons["icon_pistol"];
            pistol.category = ItemCategory.Weapon;
            pistol.basePrice = 130;
            pistol.sellRatio = 0.4f;
            pistol.maxStack = 1;
            pistol.weaponModel = models["pistol"];
            pistol.holdPosition = new Vector3(0.22f, -0.20f, 0.42f);
            pistol.holdRotation = Vector3.zero;
            pistol.damage = 18f;
            pistol.fireRate = 6f;
            pistol.range = 55f;
            pistol.pellets = 1;
            pistol.spread = 1.1f;
            pistol.automatic = false;
            pistol.magazineSize = 14;
            pistol.reloadTime = 1.2f;
            pistol.recoil = 1f;
            pistol.impactForce = 6f;
            pistol.tracerColor = new Color(1f, 0.88f, 0.45f);
            EditorUtility.SetDirty(pistol);
            weapons["pistol"] = pistol;

            var rifle = CreateOrReplace<WeaponData>($"{ItemsFolder}/Weapon_Fusil.asset");
            rifle.itemId = "weapon.rifle";
            rifle.displayName = "Fusil VK-7";
            rifle.description = "Automático y estable. La mejor opción cuando llegan muchos a la vez.";
            rifle.icon = _icons["icon_rifle"];
            rifle.category = ItemCategory.Weapon;
            rifle.basePrice = 460;
            rifle.sellRatio = 0.4f;
            rifle.maxStack = 1;
            rifle.weaponModel = models["rifle"];
            rifle.holdPosition = new Vector3(0.24f, -0.22f, 0.36f);
            rifle.holdRotation = Vector3.zero;
            rifle.damage = 21f;
            rifle.fireRate = 9f;
            rifle.range = 85f;
            rifle.pellets = 1;
            rifle.spread = 2.1f;
            rifle.automatic = true;
            rifle.magazineSize = 30;
            rifle.reloadTime = 1.9f;
            rifle.recoil = 1.4f;
            rifle.impactForce = 8f;
            rifle.tracerColor = new Color(0.6f, 0.95f, 1f);
            EditorUtility.SetDirty(rifle);
            weapons["rifle"] = rifle;

            var shotgun = CreateOrReplace<WeaponData>($"{ItemsFolder}/Weapon_Escopeta.asset");
            shotgun.itemId = "weapon.shotgun";
            shotgun.displayName = "Escopeta Trueno";
            shotgun.description = "Ocho perdigones por disparo. Devastadora de cerca, inútil de lejos.";
            shotgun.icon = _icons["icon_shotgun"];
            shotgun.category = ItemCategory.Weapon;
            shotgun.basePrice = 620;
            shotgun.sellRatio = 0.4f;
            shotgun.maxStack = 1;
            shotgun.weaponModel = models["shotgun"];
            shotgun.holdPosition = new Vector3(0.24f, -0.24f, 0.34f);
            shotgun.holdRotation = Vector3.zero;
            shotgun.damage = 14f;
            shotgun.fireRate = 1.4f;
            shotgun.range = 30f;
            shotgun.pellets = 8;
            shotgun.spread = 6.5f;
            shotgun.automatic = false;
            shotgun.magazineSize = 6;
            shotgun.reloadTime = 2.4f;
            shotgun.recoil = 3f;
            shotgun.impactForce = 14f;
            shotgun.tracerColor = new Color(1f, 0.7f, 0.4f);
            EditorUtility.SetDirty(shotgun);
            weapons["shotgun"] = shotgun;

            return weapons;
        }

        // ------------------------------------------------------------ enemigos

        static LootTable CreateLootTable(string file, int minMoney, int maxMoney, float moneyChance, List<LootTable.Entry> entries)
        {
            var table = CreateOrReplace<LootTable>($"{EnemiesFolder}/{file}.asset");
            table.moneyChance = moneyChance;
            table.minMoney = minMoney;
            table.maxMoney = maxMoney;
            table.entries = entries;
            EditorUtility.SetDirty(table);
            return table;
        }

        static List<EnemyData> CreateEnemies(Dictionary<string, ItemData> items)
        {
            var gruntLoot = CreateLootTable("Loot_Automata", 6, 16, 0.85f, new List<LootTable.Entry>
            {
                new LootTable.Entry { item = items["scrap"], chance = 0.55f, minAmount = 1, maxAmount = 3 },
                new LootTable.Entry { item = items["circuit"], chance = 0.18f, minAmount = 1, maxAmount = 1 },
                new LootTable.Entry { item = items["core"], chance = 0.05f, minAmount = 1, maxAmount = 1 },
                new LootTable.Entry { item = items["medkit"], chance = 0.07f, minAmount = 1, maxAmount = 1 },
                new LootTable.Entry { item = items["ammo"], chance = 0.12f, minAmount = 1, maxAmount = 1 },
            });

            var runnerLoot = CreateLootTable("Loot_Corredor", 4, 10, 0.7f, new List<LootTable.Entry>
            {
                new LootTable.Entry { item = items["scrap"], chance = 0.7f, minAmount = 1, maxAmount = 2 },
                new LootTable.Entry { item = items["circuit"], chance = 0.28f, minAmount = 1, maxAmount = 2 },
                new LootTable.Entry { item = items["ammo"], chance = 0.16f, minAmount = 1, maxAmount = 1 },
            });

            var grunt = CreateOrReplace<EnemyData>($"{EnemiesFolder}/Enemy_Automata.asset");
            grunt.enemyId = "enemy.grunt";
            grunt.displayName = "Autómata de chatarra";
            grunt.maxHealth = 55f;
            grunt.moveSpeed = 3.0f;
            grunt.damage = 9f;
            grunt.attackInterval = 1.1f;
            grunt.attackRange = 2.3f;
            grunt.detectionRange = 90f;
            grunt.bodyColor = new Color(0.78f, 0.26f, 0.22f);
            grunt.bodyScale = 1f;
            grunt.lootTable = gruntLoot;
            grunt.scoreValue = 10;
            grunt.firstWave = 1;
            grunt.spawnWeight = 1f;
            grunt.prefab = BuildEnemyPrefab(grunt, "Enemy_Automata", 2f, 0.5f, false);
            EditorUtility.SetDirty(grunt);

            var runner = CreateOrReplace<EnemyData>($"{EnemiesFolder}/Enemy_Corredor.asset");
            runner.enemyId = "enemy.runner";
            runner.displayName = "Corredor de chatarra";
            runner.maxHealth = 32f;
            runner.moveSpeed = 5.4f;
            runner.damage = 6f;
            runner.attackInterval = 0.7f;
            runner.attackRange = 2f;
            runner.detectionRange = 110f;
            runner.bodyColor = new Color(0.85f, 0.62f, 0.18f);
            runner.bodyScale = 0.85f;
            runner.lootTable = runnerLoot;
            runner.scoreValue = 8;
            runner.firstWave = 3;
            runner.spawnWeight = 0.8f;
            runner.prefab = BuildEnemyPrefab(runner, "Enemy_Corredor", 1.4f, 0.55f, true);
            EditorUtility.SetDirty(runner);

            return new List<EnemyData> { grunt, runner };
        }

        static GameObject BuildEnemyPrefab(EnemyData data, string prefabName, float colliderHeight, float colliderRadius, bool runner)
        {
            var root = new GameObject(prefabName);
            root.layer = LayerEnemy;

            var collider = root.AddComponent<CapsuleCollider>();
            collider.height = colliderHeight;
            collider.radius = colliderRadius;
            collider.center = Vector3.zero;

            var rb = root.AddComponent<Rigidbody>();
            rb.isKinematic = true;
            rb.useGravity = false;

            var visual = runner
                ? ModelFactory.BuildRunnerBody(root.transform, _materials["enemy"], _materials["enemyDark"], _materials["accent"])
                : ModelFactory.BuildGruntBody(root.transform, _materials["enemy"], _materials["enemyDark"], _materials["accent"]);
            SetLayerRecursive(root, LayerEnemy);

            var enemy = root.AddComponent<Enemy>();
            var renderers = new List<Renderer>();
            foreach (var r in visual.GetComponentsInChildren<Renderer>())
                if (r.sharedMaterial == _materials["enemy"]) renderers.Add(r);

            FieldWriter.On(enemy)
                .Ref("data", data)
                .Ref("visualRoot", visual.transform)
                .RefList("bodyRenderers", renderers)
                .Mask("groundMask", 1)
                .Apply();

            return SavePrefab(root, $"{PrefabsFolder}/{prefabName}.prefab");
        }

        static WaveConfig CreateWaveConfig(List<EnemyData> enemies)
        {
            var config = CreateOrReplace<WaveConfig>($"{ConfigFolder}/WaveConfig.asset");
            config.baseEnemyCount = 4;
            config.enemiesAddedPerWave = 2f;
            config.maxEnemiesAlive = 18;
            config.spawnInterval = 0.85f;
            config.prepTime = 25f;
            config.autoStartWaves = true;
            config.healthGrowth = 1.18f;
            config.damageGrowth = 1.12f;
            config.speedAddedPerWave = 0.12f;
            config.maxSpeedMultiplier = 2.2f;
            config.lootGrowth = 1.10f;
            config.scaleAddedPerWave = 0.015f;
            config.attackIntervalDecay = 0.97f;
            config.eliteEveryWaves = 5;
            config.eliteHealthMultiplier = 3.5f;
            config.eliteDamageMultiplier = 1.8f;
            config.eliteLootMultiplier = 3f;
            config.eliteScale = 1.5f;
            config.eliteTint = new Color(0.55f, 0.15f, 0.8f);
            config.enemyPool = new List<EnemyData>(enemies);
            EditorUtility.SetDirty(config);
            return config;
        }

        static ShopStock CreateShopStock(Dictionary<string, ItemData> items, Dictionary<string, WeaponData> weapons)
        {
            var stock = CreateOrReplace<ShopStock>($"{ConfigFolder}/ShopStock.asset");
            stock.buybackRatio = 1f;
            stock.entries = new List<ShopStock.Entry>
            {
                new ShopStock.Entry { item = items["medkit"], stock = -1, priceMultiplier = 1f, unlockWave = 1 },
                new ShopStock.Entry { item = items["ammo"], stock = -1, priceMultiplier = 1f, unlockWave = 1 },
                new ShopStock.Entry { item = weapons["pistol"], stock = -1, priceMultiplier = 1f, unlockWave = 1 },
                new ShopStock.Entry { item = weapons["rifle"], stock = 3, priceMultiplier = 1f, unlockWave = 2 },
                new ShopStock.Entry { item = weapons["shotgun"], stock = 2, priceMultiplier = 1f, unlockWave = 3 },
            };
            EditorUtility.SetDirty(stock);
            return stock;
        }

        // ------------------------------------------------------------- jugador

        static GameObject CreatePlayerPrefab(WeaponData starter, Dictionary<string, ItemData> items)
        {
            var root = new GameObject("Player");
            root.layer = LayerPlayer;
            root.tag = "Player";

            var cc = root.AddComponent<CharacterController>();
            cc.height = 1.8f;
            cc.radius = 0.35f;
            cc.center = new Vector3(0f, 0.9f, 0f);
            cc.slopeLimit = 50f;
            cc.stepOffset = 0.4f;

            var pivot = ModelFactory.Empty("CameraPivot", root.transform, new Vector3(0f, 1.65f, 0f));
            var camGo = new GameObject("PlayerCamera");
            camGo.transform.SetParent(pivot, false);
            camGo.tag = "MainCamera";
            var cam = camGo.AddComponent<Camera>();
            cam.fieldOfView = 72f;
            cam.nearClipPlane = 0.03f;
            cam.farClipPlane = 400f;
            camGo.AddComponent<AudioListener>();

            var socket = ModelFactory.Empty("WeaponSocket", camGo.transform, Vector3.zero);
            socket.gameObject.layer = LayerPlayer;

            var controller = root.AddComponent<PlayerController>();
            var health = root.AddComponent<PlayerHealth>();
            var inventory = root.AddComponent<PlayerInventory>();
            var wallet = root.AddComponent<Wallet>();
            var equipment = root.AddComponent<PlayerEquipment>();
            var weapon = root.AddComponent<WeaponController>();
            var loadout = root.AddComponent<StartingLoadout>();

            FieldWriter.On(controller).Ref("cameraPivot", pivot).Apply();
            FieldWriter.On(health).Float("maxHealth", 120f).Float("regenPerSecond", 3f).Float("regenDelay", 5f).Apply();
            FieldWriter.On(inventory).Int("slotCount", 24).Apply();
            FieldWriter.On(wallet).Int("money", 250).Apply();
            FieldWriter.On(equipment).Ref("weaponSocket", socket).Ref("startingWeapon", starter).Apply();
            FieldWriter.On(weapon)
                .Ref("aimCamera", cam)
                .Mask("hitMask", ~((1 << LayerPlayer) | (1 << LayerLoot)))
                .Apply();

            // Objetos iniciales.
            var so = new SerializedObject(loadout);
            var entries = so.FindProperty("entries");
            var startItems = new (ItemData item, int amount)[]
            {
                (starter, 1),
                (items["medkit"], 2),
                (items["ammo"], 1),
                (items["scrap"], 3),
            };
            entries.arraySize = startItems.Length;
            for (int i = 0; i < startItems.Length; i++)
            {
                var e = entries.GetArrayElementAtIndex(i);
                e.FindPropertyRelative("item").objectReferenceValue = startItems[i].item;
                e.FindPropertyRelative("amount").intValue = startItems[i].amount;
            }
            so.ApplyModifiedPropertiesWithoutUndo();

            return SavePrefab(root, $"{PrefabsFolder}/Player.prefab");
        }

        static void SetLayerRecursive(GameObject go, int layer)
        {
            go.layer = layer;
            foreach (Transform child in go.transform) SetLayerRecursive(child.gameObject, layer);
        }

        // ------------------------------------------------------------ database

        static GameDatabase CreateDatabase(Dictionary<string, ItemData> items, Dictionary<string, WeaponData> weapons,
            List<EnemyData> enemies, WaveConfig waveConfig, GameObject lootPrefab)
        {
            var db = CreateOrReplace<GameDatabase>(DatabasePath);
            db.items = new List<ItemData>(items.Values);
            db.weapons = new List<WeaponData>(weapons.Values);
            db.enemies = new List<EnemyData>(enemies);
            db.waveConfig = waveConfig;
            db.starterWeapon = weapons["pistol"];
            db.lootPickupPrefab = lootPrefab;
            db.moneyPickupPrefab = lootPrefab;
            db.tracerMaterial = _materials["tracer"];
            db.impactMaterial = _materials["impact"];
            EditorUtility.SetDirty(db);
            return db;
        }

        // -------------------------------------------------------------- escena

        static void BuildScene(GameObject playerPrefab, GameDatabase database, WaveConfig waveConfig, ShopStock shopStock, bool openScene)
        {
            var previous = SceneManager.GetActiveScene();
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Additive);
            SceneManager.SetActiveScene(scene);

            // Iluminación.
            var lightGo = new GameObject("Directional Light");
            var light = lightGo.AddComponent<Light>();
            light.type = LightType.Directional;
            light.intensity = 1.15f;
            light.color = new Color(1f, 0.96f, 0.88f);
            light.shadows = LightShadows.Soft;
            lightGo.transform.rotation = Quaternion.Euler(48f, -35f, 0f);

            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(0.35f, 0.42f, 0.55f);
            RenderSettings.ambientEquatorColor = new Color(0.22f, 0.24f, 0.30f);
            RenderSettings.ambientGroundColor = new Color(0.10f, 0.10f, 0.12f);
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.Linear;
            RenderSettings.fogColor = new Color(0.13f, 0.15f, 0.19f);
            RenderSettings.fogStartDistance = 45f;
            RenderSettings.fogEndDistance = 160f;
            var skybox = AssetDatabase.GetBuiltinExtraResource<Material>("Default-Skybox.mat");
            if (skybox != null) RenderSettings.skybox = skybox;

            // Arena.
            var arena = new GameObject("Arena");
            ModelFactory.Part("Ground", PrimitiveType.Cube, arena.transform, new Vector3(0f, -0.5f, 0f), new Vector3(70f, 1f, 70f), _materials["ground"]);
            arena.transform.Find("Ground").gameObject.AddComponent<BoxCollider>();

            float half = 35f;
            CreateWall(arena.transform, new Vector3(0f, 2f, half), new Vector3(70f, 4f, 1f));
            CreateWall(arena.transform, new Vector3(0f, 2f, -half), new Vector3(70f, 4f, 1f));
            CreateWall(arena.transform, new Vector3(half, 2f, 0f), new Vector3(1f, 4f, 70f));
            CreateWall(arena.transform, new Vector3(-half, 2f, 0f), new Vector3(1f, 4f, 70f));

            // Coberturas.
            var rng = new System.Random(7);
            for (int i = 0; i < 14; i++)
            {
                float angle = (float)(rng.NextDouble() * Mathf.PI * 2f);
                float radius = 8f + (float)rng.NextDouble() * 20f;
                var pos = new Vector3(Mathf.Cos(angle) * radius, 0f, Mathf.Sin(angle) * radius);
                var size = new Vector3(1.5f + (float)rng.NextDouble() * 3f, 1f + (float)rng.NextDouble() * 2.5f, 1.5f + (float)rng.NextDouble() * 3f);
                var block = ModelFactory.Part($"Cover_{i}", PrimitiveType.Cube, arena.transform,
                    pos + Vector3.up * (size.y * 0.5f), size, _materials["cover"],
                    new Vector3(0f, (float)rng.NextDouble() * 90f, 0f));
                block.AddComponent<BoxCollider>();
            }

            // Marcas del suelo.
            ModelFactory.Part("Plaza", PrimitiveType.Cylinder, arena.transform, new Vector3(0f, 0.01f, 0f), new Vector3(18f, 0.01f, 18f), _materials["grid"]);

            // Tienda.
            var kiosk = ModelFactory.BuildShopKiosk(_materials["wall"], _materials["gunDark"], _materials["accent"], _materials["wood"]);
            kiosk.transform.position = new Vector3(0f, 0f, 12f);
            kiosk.transform.rotation = Quaternion.Euler(0f, 180f, 0f);
            var kioskCollider = kiosk.transform.Find("Base").gameObject.AddComponent<BoxCollider>();
            kioskCollider.enabled = true;
            var shopZone = kiosk.AddComponent<ShopZone>();
            FieldWriter.On(shopZone)
                .Float("radius", 6f)
                .Ref("visual", kiosk.transform.Find("Hologram"))
                .Apply();

            // Puntos de aparición.
            var spawnRoot = new GameObject("SpawnPoints");
            var spawnPoints = new List<Transform>();
            for (int i = 0; i < 10; i++)
            {
                float angle = i / 10f * Mathf.PI * 2f;
                var go = new GameObject($"Spawn_{i}");
                go.transform.SetParent(spawnRoot.transform, false);
                go.transform.position = new Vector3(Mathf.Cos(angle), 0f, Mathf.Sin(angle)) * 27f + Vector3.up;
                spawnPoints.Add(go.transform);
            }

            // Jugador.
            var player = (GameObject)PrefabUtility.InstantiatePrefab(playerPrefab, scene);
            player.transform.position = new Vector3(0f, 0.2f, -4f);
            var playerController = player.GetComponent<PlayerController>();

            // Sistemas.
            var systems = new GameObject("GameSystems");
            var gameManager = systems.AddComponent<GameManager>();
            FieldWriter.On(gameManager).Ref("database", database).Ref("player", playerController).Apply();

            var waveManager = systems.AddComponent<WaveManager>();
            FieldWriter.On(waveManager)
                .Ref("config", waveConfig)
                .RefList("spawnPoints", spawnPoints)
                .Ref("arenaCenter", arena.transform)
                .Float("fallbackSpawnRadius", 27f)
                .Apply();

            var shopController = systems.AddComponent<ShopController>();
            FieldWriter.On(shopController)
                .Ref("stock", shopStock)
                .Ref("inventory", player.GetComponent<PlayerInventory>())
                .Ref("wallet", player.GetComponent<Wallet>())
                .Apply();

            // Interfaz.
            var uiGo = new GameObject("GameUI");
            var gameUi = uiGo.AddComponent<GameUI>();
            FieldWriter.On(gameUi).Ref("player", playerController).Apply();

            EditorSceneManager.MarkSceneDirty(scene);
            EditorSceneManager.SaveScene(scene, ScenePath);

            AddSceneToBuildSettings(ScenePath);

            bool previousValid = previous.IsValid() && previous != scene;
            bool canOpen = openScene || (previousValid && !previous.isDirty);
            if (previousValid) SceneManager.SetActiveScene(previous);
            EditorSceneManager.CloseScene(scene, true);

            if (canOpen && EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene(ScenePath);
        }

        static void CreateWall(Transform parent, Vector3 position, Vector3 size)
        {
            var wall = ModelFactory.Part("Wall", PrimitiveType.Cube, parent, position, size, _materials["wall"]);
            wall.AddComponent<BoxCollider>();
        }

        static void AddSceneToBuildSettings(string path)
        {
            var scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
            foreach (var s in scenes)
                if (s.path == path) return;
            scenes.Insert(0, new EditorBuildSettingsScene(path, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }
    }
}
